### ISSUE TITLE
Attribute "Unique" auto create index

### ISSUE THREAD

**Issue by gabriele-v** [praeclarum/sqlite-net#419] opened 2016-04-25 07:56 UTC
If I add attribute Unique to a field, I would expect that it creates table with unique field, instead it creates a unique index on that column.
It's about the same, but it should add an index only if explicit declared, or there is a way that I could obtain expected result with other attributes?

Code:

```
[Table("ACCOUNTLIST_V1")]
    public class Account : IEntity
    {
        public Account()
        {
        }

        [Column("ACCOUNTID"),
            PrimaryKey,
            AutoIncrement
            NotNull]
        public int Id { get; set; }

        [Column("ACCOUNTNAME"),
            NotNull,
            Collation("NOCASE"),
            Unique]
        public string Name { get; set; }
    }
```

Expected behaviour:

```
CREATE TABLE ACCOUNTLIST_V1 (
    ACCOUNTID    INTEGER PRIMARY KEY AUTOINCREMENT
                         NOT NULL,
    ACCOUNTNAME VARCHAR NOT NULL
                         COLLATE NOCASE
                         UNIQUE
);
```

Actual behaviour:

```
CREATE TABLE ACCOUNTLIST_V1 (
    ACCOUNTID    INTEGER PRIMARY KEY AUTOINCREMENT
                         NOT NULL,
    ACCOUNTNAME VARCHAR NOT NULL
                         COLLATE NOCASE
);

CREATE UNIQUE INDEX ACCOUNTNAME ON ACCOUNTLIST_V1 (
    Name
);
```

**Comment by praeclarum** [comment] 2017-08-02 14:13
This is working by design as there really is no difference. The named index does however have the benefit of droppable later. I am going to close this for now but may revisit it later. Thanks!

**Closed by praeclarum** 2017-08-02 14:13 UTC
