### ISSUE TITLE
Can not create a table with multiple primary key with SQLiteConnection.CreateTable<>()

### ISSUE THREAD

**Issue by lionpham** [praeclarum/sqlite-net#282] opened 2014-05-13 18:30 UTC
I have an entity:

```
class Entity
    {
        [PrimaryKey]
        public int FirstKey { get; set; }

        [PrimaryKey]
        public int SecondKey { get; set; }
    }
```

I use SQLiteConnection.CreateTable<>() to create table:

```
SQLiteConnection.CreateTable<Entity>();
```

However, I got the following error: table "Entity" has more than one primary key.

Please help. Thank you.

**Comment by praeclarum** [comment] 2017-08-13 00:16
Closing this as a duplicate of many issues including #280

**Closed by praeclarum** 2017-08-13 00:16 UTC
