### ISSUE TITLE
Version numbers in netstandard1.1 and portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10

### ISSUE THREAD

**Issue by JKennedy24** [praeclarum/sqlite-net#601] opened 2017-08-09 15:20 UTC
in the nuget package
**netStandard1.1**
Version of the pcl is 1.0.0

**portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10** 
version of pcl is 1.4.118

This causes an error because it cannot match the correct version:

> Could not load file or assembly 'SQLite-net, Version=1.4.118.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Only seems to affect UWP. See:

https://stackoverflow.com/questions/45497992/pcl-vs-net-standard-library-for-sqlite-in-uwp
https://stackoverflow.com/questions/45418669/xamarin-forms-pcl-assemly-issue

I think to cause this use the old style PCL libs with a Xamarin project

**Comment by markleavesley** [comment] 2017-08-09 22:21
I have just updated all my nuget packages to latest and am also getting this error in UWP. Same with 1.5.151-beta. In my bin\x86\debug folder SQLite-net.dll is version 1.0.0. The four SQLitePCLRaw* DLLs also all report version 1.0.0.

**Comment by praeclarum** [comment] 2017-08-10 03:54
Oh darn, I'll take a look!

**Comment by kwoodie** [comment] 2017-08-12 18:31
I am seeing the same issue on UWP.

**Comment by praeclarum** [comment] 2017-08-12 18:41
This should be fixed in `1.5.166-beta`

Please re-open if it's not.

**Closed by praeclarum** 2017-08-12 18:41 UTC
Labels: Bug

**Comment by kwoodie** [comment] 2017-08-12 20:39
Just pulled and tested.  Seems to be resolved.  Thanks!

**Comment by markleavesley** [comment] 2017-08-12 21:38
Using nuget with 1.5.166-beta and confirm fixed.

**Comment by Tazz85** [comment] 2017-08-15 06:01
Also fixed in the Release-Version 1.4.118?

**Comment by maxal1917** [comment] 2017-08-17 02:24
https://stackoverflow.com/questions/45497992/pcl-vs-net-standard-library-for-sqlite-in-uwp - I submitted it with 1.4.118

**Comment by xleon** [comment] 2017-09-10 14:32
It´s working on https://www.nuget.org/packages/sqlite-net-pcl/1.5.166-beta, at least in UWP

**Comment by yschkatula** [comment] 2017-10-26 16:16
I can confirm 1.5.166-beta solves the issue for UWP.

**Comment by JKennedy24** [comment] 2018-01-16 16:35
I just fell into a bug I'd already reported. I only found by googling. This bug shouldnt really be closed untill beta is stable IMO

**Comment by jernelson7** [comment] 2018-01-26 13:47
I seem to be blocked by this issue. I have my SQLite model in a .NET Standard 2.0 project which is referenced by a UWP app. I can't update the nuget reference in the .NET Standard project past 1.4.118 (the beta is not available as an option). If I update the nuget reference in the UWP project, I get a crash because some signatures have changed:

> System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Int32 SQLite.SQLiteConnection.CreateTable(SQLite.CreateFlags)'.

Can you please fix the assembly reference issue in the stable branch, or else make the beta version available for .NET Standard projects?

**Comment by symibsoft** [comment] 2018-03-07 14:48
Hi,
It is possible to have a Sqlite-Net version that works on both UWP and Android platform?
In order to have all androids SO (5,6,7) working fine, I have to use the 1.5.166-beta version and for the UWP I must use the stable version 1.4.118.0 (because if I use the 1.5.166-beta in UWP i get the error Method not found: 'Int32 SQLite.SQLiteConnection.CreateTable).

The problem is that I have the same PCL project (the model) shared between the two platform projects and I need ONE version that works on both.

**Comment by maxal1917** [comment] 2018-03-07 23:09
I'm on 1.5.166-beta for both UWP and Android. Don't have issues with UWP, and I do have code that creates table, but I use CreateTableAsync

**Comment by symibsoft** [comment] 2018-03-08 09:49
Hi Maxal!,
This morning I tried again installing the sqlite-net-pcl package 1.5.166-beta on all my projects,
Before this, I removed all sqlite packages installed in the past on all projects, so I could start from scratch.

Surprisingly now it works !! No errors on both platform and on Android it works well on both 5/6/7 SO version.
I suppose that some sql-lite additional packages remained on my project reference, maybe when I migrated the project from WinRT to UWP technology.

Thank you! without your encourage I do not know if I would try again :).
