### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by BartoszCichecki** [praeclarum/sqlite-net#477] opened 2016-11-24 12:37 UTC
When do you plan to add .NET Standard support?

**Comment by tmm360** [comment] 2016-11-24 14:07
+1

**Comment by praeclarum** [comment] 2016-11-25 16:33
Once 2.0 is out. That said, I'll probably still go through sqlite.raw so will have to match @ericsink's schedule.

**Comment by ericsink** [comment] 2016-11-25 16:35
FYI, SQLitePCL.raw already has netstandard support.

**Comment by praeclarum** [comment] 2016-11-26 21:44
Cool. I will follow your lead then!

**Comment by guiwaltricke** [comment] 2016-12-14 23:13
+1 We installed, but the lib do not compile, errors about directivies USE_NEW_REFLECTION_API @praeclarum do you have any plans to support netstandard? 

thanks

**Comment by AArnott** [comment] 2017-01-16 00:04
What I gather based on the fact that this package already supports `portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10` (effectively netstandard1.1 if I'm not mistaken) is that the only thing this package lacks is a folder called `netstandard1.1` that is a duplicate of the portable folder.

**Comment by AArnott** [comment] 2017-01-16 00:11
Yup: I was able to workaround this limitation by adding this tag to my .NET SDK project file in VS2017 RC:

```xml
<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.6' ">$(PackageTargetFallback);portable-net45+wp8+wpa81+win8</PackageTargetFallback>
```

**Comment by praeclarum** [comment] 2017-01-16 17:47
Thanks for the tip - I'd been wrestling with creating a new project. Good to know the binaries work.

**Comment by praeclarum** [comment] 2017-01-16 18:27
Fixed in 66fedfcb45a527c8aeaba4ed813ad7aef2b39d3c

Released as 1.3.0.

Let's hope I got this right!

**Closed by praeclarum** 2017-01-16 18:27 UTC
Labels: Feature

**Comment by AArnott** [comment] 2017-01-16 19:11
@praeclarum, I'm afraid 1.3.0 is broken. I added notes to 66fedfc.

**Comment by praeclarum** [comment] 2017-01-16 20:59
Yeah I got worries about the binary trick so switched the project over to .NET Standard. I thought the world was ready for Standard-only but I was wrong :-)

Thanks for all the help!

**Comment by AArnott** [comment] 2017-01-17 00:47
It's not really a 'trick'. The binaries are equivalent. Compiling for netstandard1.1 or for the PCL profile you already were just limit the API surface area you compile against. And the PCL profile you were compiling for is equivalent to netstandard1.1. So advertising this fact in your nuget package is perfectly appropriate.
Honestly, if nuget were a bit smarter, it would recognize that when someone targets .netstandard1.1, they should be able to just consume the PCL profile you're targeting without requiring that your package be updated. I don't know why they don't just do that as it seems like it would be pretty easy.
